### ISSUE TITLE
US-01.01: Realizar registro de reunião [Monitor]

### ISSUE THREAD

**Issue by viniciusbandeira** [group-4-TecProg-2017-1/WebProject#1]
Eu como monitor desejo realizar o registro de uma monitoria com intuito de apresentar as informações referentes a monitoria. 

Critério de aceitação 1: A monitoria deve possuir os seguintes campos para a validação da monitoria a ser realizada. 
Local, conteúdo abordado, horário de inicio e duração, disciplina, nome de outros monitores responsáveis.

Critério de aceitação 2: A monitoria deverá ser cadastrada de duas formas, uma monitoria fixa semanalmente ou como uma monitoria eventual.

**Comment by Jefersonalves** [comment]
Comentário para testar integração com o slack
